services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: django-blog:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:



