# Generated by Django 5.2.1 on 2025-05-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('approve_comment', 'Can approve comment'), ('hide_comment', 'Can hide comment')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('approve_post', 'Can approve post'), ('hide_post', 'Can hide post')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_user_list', 'Can view user list'), ('edit_user', 'Can edit user')]},
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('R', 'Refused'), ('H', 'Hidden')], default='P', max_length=1),
        ),
    ]
