# Generated by Django 5.2.1 on 2025-05-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('approve_post', 'Can approve post')]},
        ),
    ]
