# Generated by Django 5.2.1 on 2025-05-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_shown',
            field=models.BooleanField(default=False),
        ),
    ]
